version: "3" # docker version
services: # Just a container
      fastapi: # Container or Service name
          command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
          # build: . # Build an image for us if it doesn't exist
          build: laubenjunior/fastapi
          depends_on: # Tells docker to start the postgres container first before the fastapi container
              - postgres
          ports:
              - 8090:8000 #<port on localhost>:<port on container>
          # env_file: 
          #     - ./.env 

        #   volumes:
        #      - ./:/usr/src/app:ro #sync the folders and 'ro' means read only and the container can't change the files.

        #   command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
          environment: 
              - DATABASE_HOSTNAME=${DATABASE_HOSTNAME} # Resolves to the IP Address of container postgres on line 19
              - DATABASE_PORT=${DATABASE_PORT}
              - DATABASE_PASSWORD=${DATABASE_PASSWORD}
              - DATABASE_NAME=${DATABASE_NAME} 
              - DATABASE_USERNAME=${DATABASE_USERNAME}
              - SECRET_KEY=${SECRET_KEY}
              - ALGORITHM=${ALGORITHM}
              - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

      postgres:
          image: postgres
          environment:
              - POSTGRES_PASSWORD=${DATABASE_PASSWORD} 
              - POSTGRES_DB=${DATABASE_NAME} 
          volumes:
              - postgres-db:/var/lib/postgresql/data # Path in the container that postgres is going to write to. 

volumes:
            postgres-db: