name: Build and Deploy Code # Workflow name 

on: [push, pull_request] # What should trigger our workflow to run | Run on all branches 
  # push: # Specify the branch that should run when you push or pull 
  #   branches:
  #     - "main"
  # pull_request: 
  #   branches:
  #     - "test_branch"

jobs: # Create a job. A job is a set of steps that execute on the same runner 
  job1:env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: Lloverusatumu3
      DATABASE_NAME: fastapi 
      DATABASE_USERNAME: postgres 
      SECRET_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5cswt
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 120
    runs-on: ubuntu-18.04 # Machine on which the job will run on 
    # Provide a list of steps 
    steps: 
      - name: pulling git repo 
        uses: actions/checkout@v3 # Actual command to run 
      # - name: say hi to lauben 
      #   run: echo "Lauben" # Run a command e.g echo "Lauben" 
      - name: Install python version 3.10.0 
        uses: actions/setup-python@v3 
        with: 
          python-version: '3.10.0'
      - name: update pip 
        run: python -m pip install --upgrade pip 
      - name: Install all dependencies 
        run: pip install -r requirements.txt 
      # Run pytest 
      - name: test with pytest 
        run: | # Pipe if you want to run a list of commands 
          pip install pytest 
          pytest 